# Generated by Django 6.0.5 on 2026-06-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_department_student_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "student_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="app.student",
                    ),
                ),
            ],
        ),
    ]
